'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const ConversionHub=require('../conversionhub');
const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'..','public','index.html'),'utf8');
let e=ConversionHub.normalizeEvent({type:'lead',source:'ga4',quantity:7,externalEventId:'x'});
assert.equal(e.quantity,7);
assert(server.includes("GA4_CALLBACK_PATH='/api/integrations/ga4/callback'"));
assert(server.includes('analytics.readonly'));
assert(server.includes('analyticsdata.googleapis.com/v1beta/properties/'));
assert(server.includes("'/api/integrations/ga4/sync'"));
assert(server.includes("'/api/conversions/site/events'"));
assert(server.includes("provider='siteapi'"));
assert(server.includes('SUM(quantity)'));
assert(app.includes("['crm','CRM','Hub']"));
assert(app.includes('openGa4Manager'));
assert(app.includes('openConnectorHub'));
assert(app.includes('openSiteApiManager'));
assert(app.includes("['siteapi','Dados do seu site']"));
assert(app.includes('O que você quer acompanhar?'));
assert(app.includes('Como seu site foi criado?'));
assert(app.includes('/api/integrations/siteapi/settings'));
assert(server.includes("'/api/integrations/siteapi/settings'"));
assert(server.includes('selectedEvents'));
assert(server.includes('Este tipo de evento não está habilitado'));
assert(!app.includes("['ga4','Google Analytics 4','Em breve']"));
assert(html.includes('v102'));
console.log('conversion sources tests: ok');
